export default function getAllProducts() {
  // Enhanced product data
  const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      category: "Electronics",
      price: 99.99,
      stock: 45,
      status: "In Stock",
      sku: "WH-001",
      supplier: "AudioTech",
      dateAdded: "2024-01-15",
      image:
        "https://www.startech.com.bd/image/cache/catalog/headphone/hoco/w46-charm/w46-charm-01-500x500.webp",
      rating: 4.8,
      sales: 234,
      trending: true,
    },
    {
      id: 2,
      name: "Smart Watch",
      category: "Electronics",
      price: 199.99,
      stock: 12,
      status: "Low Stock",
      sku: "SW-002",
      supplier: "TechCorp",
      dateAdded: "2024-01-10",
      image:
        "https://www.startech.com.bd/image/cache/catalog/smart-watch/colmi/p28-plus/p28-plus-black-official-500x500.webp",
      rating: 4.6,
      sales: 156,
      trending: false,
    },
    {
      id: 3,
      name: "Laptop Stand",
      category: "Accessories",
      price: 49.99,
      stock: 67,
      status: "In Stock",
      sku: "LS-003",
      supplier: "OfficeSupply",
      dateAdded: "2024-01-08",
      image:
        "https://www.startech.com.bd/image/cache/catalog/laptop-stand/laptop-stand-6-angles/adjustable-laptop-stand-silver-005-500x500.webp",
      rating: 4.3,
      sales: 89,
      trending: false,
    },
    {
      id: 4,
      name: "USB-C Cable",
      category: "Accessories",
      price: 19.99,
      stock: 156,
      status: "In Stock",
      sku: "UC-004",
      supplier: "CableCo",
      dateAdded: "2024-01-05",
      image:
        "https://www.startech.com.bd/image/cache/catalog/cable/riversong/ct56-c/cm56-alpha-03-b-500x500.webp",
      rating: 4.1,
      sales: 445,
      trending: true,
    },
    {
      id: 5,
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 79.99,
      stock: 0,
      status: "Out of Stock",
      sku: "BS-005",
      supplier: "SoundTech",
      dateAdded: "2024-01-03",
      image:
        "https://www.startech.com.bd/image/cache/catalog/speaker/hoco/bs60/bs60-01-500x500.webp",
      rating: 4.7,
      sales: 178,
      trending: false,
    },
    {
      id: 6,
      name: "Phone Case",
      category: "Accessories",
      price: 24.99,
      stock: 89,
      status: "In Stock",
      sku: "PC-006",
      supplier: "ProtectCo",
      dateAdded: "2024-01-01",
      image:
        "https://adminapi.applegadgetsbd.com/storage/media/large/Galaxy-S22+-Clear-Cover---Transparent-(2)-4874.jpg",
      rating: 4.4,
      sales: 267,
      trending: true,
    },
    {
      id: 7,
      name: "Gaming Mouse",
      category: "Electronics",
      price: 59.99,
      stock: 34,
      status: "In Stock",
      sku: "GM-007",
      supplier: "GameTech",
      dateAdded: "2023-12-28",
      image:
        "https://www.startech.com.bd/image/cache/catalog/mouse/havit/ms1035/ms1035-01-500x500.webp",
      rating: 4.9,
      sales: 123,
      trending: false,
    },
    {
      id: 8,
      name: "Desk Lamp",
      category: "Furniture",
      price: 59.99,
      stock: 18,
      status: "Low Stock",
      sku: "DL-008",
      supplier: "LightCorp",
      dateAdded: "2023-12-25",
      image:
        "https://www.gadstyle.com/wp-content/uploads/2025/05/usb-rechargeable-table-lamp-touch-dimming-portable-night-light-2600mah-1.webp",
      rating: 4.2,
      sales: 67,
      trending: false,
    },
  ];

  return products;
}
