export default function getAllProducts() {
  // Enhanced product data
  const products = [
    {
      id: 1,
      name: "Wireless Headphones",
      category: "Electronics",
      price: 99.99,
      stock: 45,
      status: "In Stock",
      sku: "WH-001",
      supplier: "AudioTech",
      dateAdded: "2024-01-15",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.8,
      sales: 234,
      trending: true,
    },
    {
      id: 2,
      name: "Smart Watch",
      category: "Electronics",
      price: 199.99,
      stock: 12,
      status: "Low Stock",
      sku: "SW-002",
      supplier: "TechCorp",
      dateAdded: "2024-01-10",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.6,
      sales: 156,
      trending: false,
    },
    {
      id: 3,
      name: "Laptop Stand",
      category: "Accessories",
      price: 49.99,
      stock: 67,
      status: "In Stock",
      sku: "LS-003",
      supplier: "OfficeSupply",
      dateAdded: "2024-01-08",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.3,
      sales: 89,
      trending: false,
    },
    {
      id: 4,
      name: "USB-C Cable",
      category: "Accessories",
      price: 19.99,
      stock: 156,
      status: "In Stock",
      sku: "UC-004",
      supplier: "CableCo",
      dateAdded: "2024-01-05",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.1,
      sales: 445,
      trending: true,
    },
    {
      id: 5,
      name: "Bluetooth Speaker",
      category: "Electronics",
      price: 79.99,
      stock: 0,
      status: "Out of Stock",
      sku: "BS-005",
      supplier: "SoundTech",
      dateAdded: "2024-01-03",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.7,
      sales: 178,
      trending: false,
    },
    {
      id: 6,
      name: "Phone Case",
      category: "Accessories",
      price: 24.99,
      stock: 89,
      status: "In Stock",
      sku: "PC-006",
      supplier: "ProtectCo",
      dateAdded: "2024-01-01",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.4,
      sales: 267,
      trending: true,
    },
    {
      id: 7,
      name: "Gaming Mouse",
      category: "Electronics",
      price: 59.99,
      stock: 34,
      status: "In Stock",
      sku: "GM-007",
      supplier: "GameTech",
      dateAdded: "2023-12-28",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.9,
      sales: 123,
      trending: false,
    },
    {
      id: 8,
      name: "Desk Lamp",
      category: "Furniture",
      price: 39.99,
      stock: 18,
      status: "Low Stock",
      sku: "DL-008",
      supplier: "LightCorp",
      dateAdded: "2023-12-25",
      image: "/placeholder.svg?height=200&width=200",
      rating: 4.2,
      sales: 67,
      trending: false,
    },
  ];

  return products;
}
